[project]
name = "mindfuly"
version = "0.0.1"
authors = [
  { name="Jovian Kuntjoro", email="jzk@sfu.ca" },
  { name="Kunal Joshi", email="kja81@sfu.ca" },
  { name="Eugene Park", email="epa44@sfu.ca" },
  { name="Chris Pratt", email="ccp7@sfu.ca" },
  { name="Quang Vo", email="tqv1@sfu.ca" },
]
description = "A web-based wellness tracker"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "alembic>=1.16.5",
    "dotenv>=0.9.9",
    "email-validator>=2.0.0",
    "fastapi>=0.117.1",
    "nicegui>=2.24.2",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.9",
    "pytest-cov>=7.0.0",
    "sqlalchemy>=2.0.43",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/mindfuly"]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "ruff>=0.13.2",
]



